version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kyiv-fuel:latest
    container_name: kyiv-fuel-api
    command: npm run start:dev
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
